collections:
  example:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name
  start:
    output: true
    permalink: /:collection/:name

jekyll-archives:
  enabled: 'all'
  layout: 'default'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
